# Generated by Django 5.0 on 2024-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_like_ip_address_alter_like_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
